# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:NAA0RkFWxkeD99dRFj2C19BjKXhG8WiIFGRrg1vHFd3kWL/cD0h5/rLK7m5oU+bit/JCvbCxe/QoAqSgOKN53U3sOeW8V0FkElce8J3ApKovI1TXKc7ElIPjQOwTiwUwBI3ecW0lp1TG7WJec5SElf6R2fK8rjshFgjLvd4p/TWc68eQ9Y2W20IRc9tFCZd4PU41GqrlWiKQim1var6oqrTnyaf+wEFaImwG+SBOF/73UPemgA==,iv:fHIvwERJZoXWwUYrYJdf9GsnzZcZ4jTSQBnItjknOks=,tag:Kf/Es/5+qYrI7/wdlIh0gg==,type:str]
sops:
  age:
    - recipient: age15z4yxqz3lppqmrg3tg0jtzw3e33ruledmag5wz0fw32cqrw335cqa2kvft
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzMW5zcVVENlBDZHAwRUF6
        NjBDVzZ2bHBJcVlhYTF6WFEwdFNSMmhMU3hjCnNZOUtLS3Zta05reHlWZzIrZUIw
        UHJDOXk1VjdrdHMxRGJnTVp1Znhaa0UKLS0tIGltZXF1aGhZc20wL1lLWWRrRGhZ
        NGZYcnZRV3dqQ0Y0SnF1WGVVQ1RTKzgKr7tbRYyhLFf5YPSyvdyXjpPMS+VtfNL6
        hLV/ce38ni9dciCpnSEggTZ7bBWVQU2qzWTSmitQng6VhRPN1m/J4Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-29T19:53:35Z"
  mac: ENC[AES256_GCM,data:XfW8tST6kcR+nyDgoGPLKWlUu6HywOadYD4OIjLgHzjHbonTeh4iSE4mILEZiivFqsGn/zINWl/RkDNeQT/LWWAeNB+6Mdo1f4IM0Wg8oWw6mvC8nVwxbexKDi1B4suzP3LMOfsF70vqBP69pVplg0MIzLoFlNkC7RVWbqXYi34=,iv:yu+UoodCuZC6PIY/6Jd5g8TXqmJ8NWo60Xa16Ni2sB8=,tag:aRq4c3GP/av8rzwoxdtmBQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
