machine:
  files:
    - content: |
        #!/bin/sh
        rm -rf /var/lib/rook
        rm -rf /var/lib/ceph
      permissions: 0744
      path: /cleanup-ceph.sh
      op: create
  tasks:
    - name: cleanup-ceph
      runner: oneshot
      command: /cleanup-ceph.sh
