# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:D8vPCUDVJL/WuaKBPkJ+jyXT7BXbgIRKKnS0RadAikQ4CCve6e6vlQ==,iv:puyEEC2/LKR1Icb5uNx+vuwOTqmf0SonIZahl+Ac8zo=,tag:tdLPFVzUVNbalDwLCCO46A==,type:str]
sops:
  age:
    - recipient: age15z4yxqz3lppqmrg3tg0jtzw3e33ruledmag5wz0fw32cqrw335cqa2kvft
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmY1hMcGcveVhVUmY2bEl0
        SUlWT0w1VVhYRkVMS1FDK1NIbG1KUWwwZHhBCnlsWnpOaFVQYURXTFRaTXIydUpx
        MWdaRjVRTDhweDdMdmwwQzByQm92bVEKLS0tIDVka1NMdjdGVE94OG5Zd2tZU1Vy
        QTlUNGpkZjB6S2UwUkR2RDBXdFNtSUEKEDo/uVbEtrq9HG0NwaYSFYH9uxPzRUi/
        PBFvmesLcUJ4bWBeK9tU8VziEhyYdomV216bUf3/vmiRzK5gh8zv2Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-29T17:56:34Z"
  mac: ENC[AES256_GCM,data:rRHjPM/NsJP3uiXZuIwuSgRwSMsjZvd5vQImnjgtZSzK6+etKPBrHfSlAU6oGEjNlDshIWppx4/5yRxnssqSu36/BlyNuQTu53hRkO6IPuNSc+Q9R5DSNkTYdmeG66eLV+nwVSVpu0EOg5/IE5g5X62yo88P24aCTwTfGF2ZCqA=,iv:ylyso+kLW1o0eXaBPtqayds8OpCkOjpnqkOu/fZdo48=,tag:5r8u2KyPdVPWL44KNpDl+Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
