# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:962h2KbmTJk0cPPRhM4uMiVb0por0w/z0MCzUIucY7E=,iv:7l4zAjCCxivXxlE+HgC1/vd0YRBFj9NCZzlaQi4P0qE=,tag:UsdQ5LFrlmtpMMCee2y/Eg==,type:str]
sops:
  age:
    - recipient: age15z4yxqz3lppqmrg3tg0jtzw3e33ruledmag5wz0fw32cqrw335cqa2kvft
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvKzcxb3VvSTVNRUNWSFJO
        ODVQTTJZSGhsbks2ZFQxQWxzMjNyUmhlUWxjCmYrTkZaTEhVdWh0WGdaQXhnRkdU
        R0Q4UTVEWmdpTThqOGdZdm1RMWpzUGcKLS0tIFNSOWNrekdXOG5JNzZRMFBoc0pW
        T3g3UjRFQ09WOFFiYXhaY2F0RzBOK1kK1MB5Bpgi9QDEH313Q3XHLRWPTJZWfeSE
        FZojMHEp2vQypgdblpFId4RVqnCimFqzEuzoncH8f5ZQPEJd1/e33Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-29T17:56:34Z"
  mac: ENC[AES256_GCM,data:uuM9dQbw//kazELSRkF+M0VKg+uk/d6fHO+/5Tl9F5PzRzTFUnwy/owoQO9uHwlR7Mf71mP/jAZbThLrQ17l5OldfeskPmy0uMZxAVMMmDzMwfJfB4nWzmSKrWusL/TI3SdjRRE+T99uX0C5aLEUzGinmtGhqKg5Psn5KpE7MZk=,iv:4XMrK9IAJbbBTCsd/tgcUwwbQaqy8NW3uGGpW3AZxso=,tag:2R+cstTrgjOFEp+Tg4gdAg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
