apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:kEw5aSj1vXRBjg51MJLaGKO7,iv:cUY0q5sS5nAt8sZP064su8rGBF/dBZYUyF37AHRB4KY=,tag:WyRUKk2UhvUHEVCVpoB0YA==,type:str]
sops:
  age:
    - recipient: age15z4yxqz3lppqmrg3tg0jtzw3e33ruledmag5wz0fw32cqrw335cqa2kvft
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTTBqVlNwY3JVTllTUXJ1
        UWFIN0h6OGh2Uit4eEtJdmt2bHgwWnR6TFhBClpDbktyYjlFaFhTTlBwdk5Va0Yv
        ellUbXdNa3kxMHZKRUhWNTcyVGhUc1EKLS0tIGp4TGNrZk52eGVOZWQ3UGhXZFAx
        WGZLWVpjSWtGaWt3eG94enAwS1AvVDAKLr/mZoeoE2+BxcVoRxhqAiON3TjzMMIG
        Sb3n/HReiXXX/DqGZ4rvg2SCeoJF1kwP4xK0ITAtV+D2FMXqckzV6A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-29T19:53:35Z"
  mac: ENC[AES256_GCM,data:czik/gmsStlh2EXd3iykv6xlqdsr9X3jLHBxW9uI0Y+x1/HP1jbWZ6fLab6Dh+bgqDF/2coRiwdV1MMBHBao6eTW/7aYN5KhkctW4K6MkGfhhvSCHjT3vhUb0A1Jk2ftCCmK+ibRrd/U4LeoZXnDO0AG4fqZGMYZZ3dLmuT7T+E=,iv:Dx/QrZ9u+gMdPD6TzW8SVUjC0MjLKM4Z2PVk43UkxwU=,tag:Y28Os5NzxYttrBtXOgawqA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
