# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.1.150:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.1.150"
  - "api.omahasolutions.net"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "cluster-1"
    ipAddress: "192.168.1.151"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/70d243b7e2cbe699e4db5e73356a2add6b4bb8e34eadba9db22c823110e79099
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "00:16:3e:f9:37:b2"
        dhcp: false
        addresses:
          - "192.168.1.151/23"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.1.3"
        mtu: 1500
        vip:
          ip: "192.168.1.150"
  - hostname: "cluster-2"
    ipAddress: "192.168.1.152"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/70d243b7e2cbe699e4db5e73356a2add6b4bb8e34eadba9db22c823110e79099
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "00:16:3e:35:10:0e"
        dhcp: false
        addresses:
          - "192.168.1.152/23"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.1.3"
        mtu: 1500
        vip:
          ip: "192.168.1.150"
  - hostname: "cluster-3"
    ipAddress: "192.168.1.153"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/70d243b7e2cbe699e4db5e73356a2add6b4bb8e34eadba9db22c823110e79099
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "00:16:3e:15:4c:ff"
        dhcp: false
        addresses:
          - "192.168.1.153/23"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.1.3"
        mtu: 1500
        vip:
          ip: "192.168.1.150"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"

